-- InterviewLens: one-time migration for candidate interview experiences.
-- Run this in Supabase SQL Editor if your existing database already has schema.sql applied.

create table if not exists public.experience_reports (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  role text not null,
  company text not null default '',
  interview_round text not null default 'Technical',
  difficulty text not null default 'Medium',
  fingerprint text not null,
  created_at timestamptz not null default now(),
  unique (question_id, fingerprint)
);

create index if not exists experience_reports_question_id_idx on public.experience_reports(question_id);
create index if not exists experience_reports_role_company_idx on public.experience_reports(role, company, created_at desc);

alter table public.experience_reports enable row level security;

-- The InterviewLens backend uses the server-side Supabase secret/service-role key.
-- Keep that key only in Vercel environment variables; never put it in browser code.
