-- InterviewLens persistent community database (Supabase/Postgres)
-- Run this once in the Supabase SQL Editor.

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  role text not null,
  question text not null,
  confirmations integer not null default 0,
  created_at timestamptz not null default now(),
  unique (role, question)
);

create table if not exists public.confirmations (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  fingerprint text not null,
  created_at timestamptz not null default now(),
  unique (question_id, fingerprint)
);

create table if not exists public.experience_reports (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  role text not null,
  company text not null default '',
  interview_round text not null default 'Technical',
  difficulty text not null default 'Medium',
  fingerprint text not null,
  created_at timestamptz not null default now(),
  unique (question_id, fingerprint)
);

create index if not exists confirmations_question_id_idx on public.confirmations(question_id);
create index if not exists questions_role_confirmations_idx on public.questions(role, confirmations desc);
create index if not exists experience_reports_question_id_idx on public.experience_reports(question_id);
create index if not exists experience_reports_role_company_idx on public.experience_reports(role, company, created_at desc);

-- Atomic confirmation: inserts only once per anonymous fingerprint and increments the count only for a new confirmation.
create or replace function public.confirm_question(p_question_id bigint, p_fingerprint text)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  new_count integer;
begin
  if not exists (select 1 from public.questions where id = p_question_id) then
    raise exception 'Question not found';
  end if;

  insert into public.confirmations(question_id, fingerprint)
  values (p_question_id, p_fingerprint)
  on conflict (question_id, fingerprint) do nothing;

  if found then
    update public.questions
      set confirmations = confirmations + 1
      where id = p_question_id
      returning confirmations into new_count;
  else
    select confirmations into new_count from public.questions where id = p_question_id;
  end if;

  return new_count;
end;
$$;

alter table public.questions enable row level security;
alter table public.confirmations enable row level security;
alter table public.experience_reports enable row level security;

-- The backend uses the server-side service-role/secret key. No public client policies are needed.
